### ISSUE TITLE
Error during WebSocket handshake: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by AlexGolovko** [AlexGolovko/UltrasonicDeeper#37]

**Comment by AlexGolovko** [comment]
Sonar log:
22:32:56.517 -> DEBUG:None:Disconnected
22:32:56.517 -> Task exception wasn't retrieved
22:32:56.517 -> future: <Task> coro= <generator object 'add_client' at 3fca82b0>
22:32:56.517 -> Traceback (most recent call last):
22:32:56.517 ->   File "uasyncio/core.py", line 1, in run_until_complete
22:32:56.517 ->   File "ws_sonar_server.py", line 27, in add_client
22:32:56.517 ->   File "protocol.py", line 193, in send
22:32:56.517 ->   File "uasyncio/stream.py", line 1, in drain
22:32:56.563 -> OSError: [Errno 104] ECONNRESET

**Comment by AlexGolovko** [comment]
fixed during refactoring
